version: '2'
services:
  db:
    image: jacobalberty/firebird:2.5-ss
    ports:
      - 3050:3050
    volumes:
      - ./data:/databases
    environment:
      ISC_PASSWORD: masterkey
      FIREBIRD_DATABASE: fcw_pool
      FIREBIRD_USER: fcw
      FIREBIRD_PASSWORD: masterkey

  db2:
    image: mysql:5.7
    ports:
      - 3386:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_DATABASE: fcw_pool
      MYSQL_USER: fcw
      MYSQL_PASSWORD: masterkey

  php:
    depends_on:
      - db
    image: fcwwebsites/php-firebird-mysql
    ports:
      - 8004:80
    volumes:
      - ./www:/usr/share/nginx/html/
    links:
      - db
      - db2
volumes:
    db_data: